pipeline{
    agent any

    environment{
        NEXUS_ADDRESS = ''
        IMAGE = ''
        TAG = ''
        DEPLOYED_CONTAINER = ''
        PROD_IP_ADD = ''
        CONTAINER_IP = ''
        CONTAINER_PORT = ''
        APP_PORT= ''
        TAR_FILE=''
    }

    stages{
        //Build Step
        //Testing
        //Artifact Archiving
        //Deployment
    }
}
